services:
    jenkins:
        build:
            context: .
        environment:
          - DOCKER_HOST=tcp://docker:2376 
          - DOCKER_CERT_PATH=/certs/client 
          - DOCKER_TLS_VERIFY=1 
        volumes:
            - ./jenkins-data:/var/jenkins_home
            - ./jenkins-docker-certs:/certs/client:ro
        ports:
            - "8080:8080"
            - "50000:50000"
  
